package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/luishenriqs/GoProject/GoExperts_Phase_5/1-GraphQL/graph/model"
)

/*
CreateCategory é o resolver GraphQL da mutation `createCategory`.

Responsabilidade:
- Receber o input `model.NewCategory` vindo da camada GraphQL.
- Persistir a categoria no banco via `r.CategoryDB.Create(...)`.
- Converter o resultado do banco para o tipo GraphQL `model.Category`, garantindo o ponteiro para `Description`.

Parâmetros:
- ctx: contexto da requisição (cancelamento, deadline e valores de request).
- input: dados da nova categoria (Name obrigatório; Description opcional via ponteiro).

Retorno:
- *model.Category: categoria criada no formato esperado pelo schema GraphQL.
- error: erro de persistência/execução caso ocorra; em caso de sucesso, nil.

Observações:
- O campo `input.Description` é ponteiro; ao desreferenciar (`*input.Description`), é necessário garantir que não seja nil.
- A variável local `Category` guarda o retorno do banco e é mapeada para o modelo GraphQL.
*/
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.NewCategory) (*model.Category, error) {
	Category, err := r.CategoryDB.Create(input.Name, *input.Description)
	if err != nil {
		return nil, err
	}
	return &model.Category{
		ID:          Category.ID,
		Name:        Category.Name,
		Description: &Category.Description,
	}, nil
}

// CreateCourse is the resolver for the createCourse field.
func (r *mutationResolver) CreateCourse(ctx context.Context, input model.NewCourse) (*model.Course, error) {
	panic(fmt.Errorf("not implemented: CreateCourse - createCourse"))
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	categories, err := r.CategoryDB.FindAll()
	if err != nil {
		return nil, err
	}

	var categoriesModel []*model.Category
	for _, category := range categories {
		categoriesModel = append(categoriesModel, &model.Category{
			ID:          category.ID,
			Name:        category.Name,
			Description: &category.Description,
		})
	}

	return categoriesModel, nil
}

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context) ([]*model.Course, error) {
	panic(fmt.Errorf("not implemented: Courses - courses"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
